### ISSUE TITLE
update rag stack to use existing WatsonX services

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/dev-rag#10]
In https://github.com/terraform-ibm-modules/terraform-ibm-watsonx-saas-da/releases/tag/v1.4.0 support was added to use existing WatsonX instance - this should be exposed in the stack

**Comment by in-1911** [comment]
Watson DA will need a fix for https://github.com/terraform-ibm-modules/terraform-ibm-watsonx-saas-da/issues/130 - the 1.4.0 is broken.

**Comment by ocofaigh** [comment]
Fixed in 1.4.1
