### ISSUE TITLE
Default value for cloud shell settings

### ISSUE THREAD

**Issue by in-1911** [terraform-ibm-modules/dev-rag#14]
### Description
Since the account infrastructure base DA [has an issue ](https://github.com/terraform-ibm-modules/terraform-ibm-iam-account-settings/issues/301) with cloud shell settings when using a service ID (or trusted profile), the default for `skip_cloud_shell_calls` should be set to `true`.

### New or affected modules

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment]
@in-1911 I guess you wan't `skip_cloud_shell_calls` to default to true in the stack? But should we expose it as a stack level input incase someone is not using service ID or TP?

**Comment by in-1911** [comment]
Technically we can expose it, but I think if we keep doing that, the stack inputs will become unmanageable.
The users still can change it at the DA level if there is a real need for that. 
In this particular case, this option is not material for the solution functionality, and I do not remember that setting used in SCC profiles I used.

The drawback of setting the default in the stack is that the current projects functionality requires a manual user's input to override it while ignoring the matching values from the environment.

The problem with leaving it enabled is that the error is rather vague and it's not even documented in the Account Infra Base that you have to turn it off if using trusted profile or a service ID for deployment.

**Comment by vburckhardt** [comment]
I'd change the settings of the account settings da rather than the stack to have a global common behavior here across all users of that da
