### ISSUE TITLE
Updates to "basic" variation

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/dev-rag#18]
- Basic should deploy the standard plan elasticsearch instance and should not deploy elser model
- The specs of the elaticsearch instance should be the lowest / cheapest possible (cpu - 0, multitenant member etc) - this should be added directly to stack_definition.json

**Comment by akocbek** [comment]
https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/pull/180
