### ISSUE TITLE
Diagram is missing Event Notifications

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/dev-rag#33]
Diagram is missing Event Notifications: https://github.com/terraform-ibm-modules/dev-rag/blob/main/reference-architecture/rag-stack.svg

While updating, review the whole content of the diagram, as it was suggest that we may want to re-order some of the content

**Comment by ajainghub** [comment]
@ocofaigh Please update these two diagrams in content:
1. Reference architecture (added wx Orchestrate to the architecture)
2. Solution components (added wx Orchestrate, Event Notifications, and reordered the stack)

![RAGPattern-Arch-noback](https://github.com/user-attachments/assets/485e2546-e786-4002-8a3f-92a341f3fd18)
![RAGPatternDAStack-noback](https://github.com/user-attachments/assets/92b1d878-0ebe-4e18-9bc2-22eabaabaf09)

**Comment by ocofaigh** [comment]
Updated diagrams coming in https://github.com/terraform-ibm-modules/dev-rag/pull/42
