### ISSUE TITLE
Review offering descriptions + features

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/dev-rag#34]
The content that is displayed in the tile is all stored in code in the ibm_cataog.json. We need to review the values for the following:

**Offering level:**
- `short_description`
- `long_description`
- `features`
![image](https://github.com/user-attachments/assets/af87a593-27c1-4eea-9fca-ae8a83c70ab4)

---
**Per variation:**
- `architecture.features` (the feature title is the smaller text, the description is the larger text)
![image](https://github.com/user-attachments/assets/f240e921-73a1-4d50-bdcd-ca7db4e766a9)

**Comment by ajainghub** [comment]
@ocofaigh
New content is now ready for title, short_description, long_description, features and variations was reviewed.
I will share separately.
