### ISSUE TITLE
Identical names for EN and SCC COS instances

### ISSUE THREAD

**Issue by in-1911** [terraform-ibm-modules/dev-rag#40]
With the default deployment of the full stack, the COS instances created for SCC and Event Notifications are provisioned with the same name (like `<prefix>-base-security-services-cos`).
We should change the default values passed to the corresponding DAs to distinguish them.

### Affected modules

*

### Terraform CLI and Terraform provider versions

* Terraform version:
* Provider version:

### Steps to reproduce (including links and screen captures)

1. Run `terraform apply`

### Anything else

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by in-1911** [comment]
![Screenshot_2024-09-11__21-35-46](https://github.com/user-attachments/assets/f3f9327c-c7e5-4a88-a5bd-c6cad73bc0e9)

**Comment by ocofaigh** [comment]
I'm updating the default name used in EN DA: https://github.com/terraform-ibm-modules/terraform-ibm-event-notifications/pull/290

**Comment by ocofaigh** [comment]
Fix is in https://github.com/terraform-ibm-modules/dev-rag/releases/tag/v0.4.1
