### ISSUE TITLE
round of testing against 2 flavors

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/dev-rag#46]
Replay existing test scenarios:
https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/issues/17#issuecomment-2069320713

**Comment by rajatagarwal-ibm** [comment]
I will be working with @iamar7 on this. I will do CE based testing, Anam can work on ROKS based testing.

**Comment by ocofaigh** [comment]
v2.0.0 is live now in the community registry
