### ISSUE TITLE
Reverse code engine / roks and alm in the stack

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/dev-rag#49]
This is needed to align conceptually with the stack diagram. Also conceptually it makes sense to have a the compute infrastructure set up before the pipeline infrastructure.

![image](https://github.com/user-attachments/assets/3e9788ed-055c-4e2b-a00c-784be72dfae4)

currently:
![image](https://github.com/user-attachments/assets/9850f711-3df3-4bf3-b465-e9175275f1d8)

**Comment by ocofaigh** [comment]
https://github.com/terraform-ibm-modules/dev-rag/pull/63
