### ISSUE TITLE
[dev rag] Update to observability DA that will deploy Cloud Logs instead of logdna

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/dev-rag#51]

**Comment by vburckhardt** [comment]
Ensure that the stack level inputs, such as "enable_platform_logs_metrics" are updated accordingly.

**Comment by ocofaigh** [comment]
@vburckhardt yes I have done that in https://github.com/terraform-ibm-modules/dev-rag/pull/52

**Comment by ocofaigh** [comment]
https://github.com/terraform-ibm-modules/dev-rag/releases/tag/v0.4.3
