### ISSUE TITLE
Essential Security - Observability Event Notifications configuration name is confusing

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/dev-rag#53]
Suggest to remove Observability from the term as it implies this is deploying the observability services, when this is actually not the case.

"Essential Security - Observability Event Notifications" -> "Essential Security - Event Notifications" 

![image](https://github.com/user-attachments/assets/290245f4-d179-4624-8fb0-c41ff846c547)

**Comment by ocofaigh** [comment]
@vburckhardt It was put there for ordering actually - cc @in-1911

**Comment by in-1911** [comment]
Yes, that was entirely to place the EN DA after logging. So if you can find an "alternative spelling" that would do that - we can change it.

**Comment by ocofaigh** [comment]
Renaming to `Essential Security - Event Notifications` since it no longer has a dependency on Observability. Infact Observability has a dependency on it now with Cloud Logs integration

**Comment by ocofaigh** [comment]
Part of https://github.com/terraform-ibm-modules/dev-rag/releases/tag/v0.4.3
