### ISSUE TITLE
incorrect required inputs in 0.4.3

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/dev-rag#61]
![image](https://github.com/user-attachments/assets/809a8062-31f8-4383-bf07-cf75fa7f444a)

**Comment by vburckhardt** [comment]
enable_platform_metrics should be on optional tab. I also do not think it is pertinent to surface logs routing regions here (can we use the value from region field)

**Comment by ocofaigh** [comment]
Addressing in https://github.com/terraform-ibm-modules/dev-rag/pull/59

**Comment by ocofaigh** [comment]
https://github.com/terraform-ibm-modules/dev-rag/releases/tag/v0.5.0
